<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15770" started-at="2018-12-03T04:00:51Z" finished-at="2018-12-03T04:01:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15770" started-at="2018-12-03T04:00:51Z" finished-at="2018-12-03T04:01:07Z">
      <class name="com.w2a.rough.TestCase2">
        <test-method status="FAIL" signature="doLogin(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.rough.TestCase2@cb644e]" name="doLogin" duration-ms="15662" started-at="2018-12-03T04:00:51Z" data-provider="getData" finished-at="2018-12-03T04:01:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[vikashkumar.101289@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lohani@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy8.sendKeys(Unknown Source)
at com.w2a.zoho.pageObjects.ZohoLoginPage.doLogin(ZohoLoginPage.java:24)
at com.w2a.rough.TestCase2.doLogin(TestCase2.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
      </class> <!-- com.w2a.rough.TestCase2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
